all:
	cc 3d_basic.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o ../bin/3d_basic
	cc hello_world.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o ../bin/test_hello_world
	cc mouse_collision.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o ../bin/mouse_collision